# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------
QT += widgets
TEMPLATE = app
TARGET = 2048
DESTDIR = ./x64/Release
CONFIG += release
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += ./GeneratedFiles
RCC_DIR += .
HEADERS += ./Game.h \
    ./Grid.h
SOURCES += ./main.cpp \
    ./Game.cpp \
    ./Grid.cpp
RESOURCES += Game.qrc
