% set default value


% --- for plot
configPlot('FontSize',      18,                ...
           'FontName',      'Times New Roman', ...
           'Position',      [2, 2, 10, 7.8],   ...
           'Units',         'centimeter',      ...
           'LineWidth',     2.5,                 ...
           'AxesLineWidth', 1.5,               ...
           'ColorOrder',    getcolor("python"));
