# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------
QT += widgets
TEMPLATE = app
TARGET = Notepad
DESTDIR = ./x64/Release
CONFIG += release
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += ./GeneratedFiles
RCC_DIR += .
HEADERS += ./Notepad.h
SOURCES += ./main.cpp \
    ./Notepad.cpp
RESOURCES += Notepad.qrc
